email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/athi" # for test: remove string '/space-jekyll-template' to ''
url: "https://athilog.github.io/athi/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
